# Build tests using the libraries installed in system
name: TestsSysLibs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install libpcap
      run: sudo apt-get install -y libpcap-dev
    
    - name: Install googletest
      run: sudo apt-get install -y libgtest-dev

    - name: Install libtins
      run: sudo apt-get install -y libtins-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DNF9_BUILD_TESTS=ON

    - name: Build Tests
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build \
          --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test/netflowtests
      # ctest -C ${{env.BUILD_TYPE}}
